### ISSUE TITLE
Suggestion / Request - Allow option to simply overwrite source files without appending them with '(fixed)'

### ISSUE THREAD

**Issue by TheWox** [innocenat/kindle-epub-fix#13]
It becomes cumbersome to remove original files, and rename many files with the '(fixed)' word appended to them. They are often interspersed as well with other books that did not require fixes. This is quite messy on a phone even using batch renaming. It would be so nice to just fix and overwrite the originals with a toggle or check box with a warning if needed.

**Comment by thomas-shirley** [comment]
I have created a [pull request](https://github.com/innocenat/kindle-epub-fix/pull/17) for this request.

**Comment by innocenat** [comment]
PR #17 accepted.
