### ISSUE TITLE
Something wrong with the netlify tool

### ISSUE THREAD

**Issue by PODKINS** [innocenat/kindle-epub-fix#23]
I use the netlify app for fixing epubs before sendiny to kindle literally every day but for the last 24 hours I keep getting the below error message which comes up instantly on uploading the epub. It doesnt take 20 seconds. Just immediate. I've tried all different files to see if it's just 1 x corrupt epub but it doesn't seem to make a difference.

**Comment by innocenat** [comment]
It seems like the image was not successfully uploaded.

**Comment by PODKINS** [comment]
[Uploading Screenshot_20241210_094038_Chrome.jpg…]()

**Comment by PODKINS** [comment]
[
![Screenshot_20241210_094038_Chrome](https://github.com/user-attachments/assets/86342268-2eea-4468-8949-d8818152c01a)
](url)

**Comment by PODKINS** [comment]
> It seems like the image was not successfully uploaded.

Apologies. I have fixed the link and uploaded a screenshot above.

**Comment by PODKINS** [comment]
It appears to be working again. Closing unless issue reappears. Thank you.
